# Generated by Django 4.0.1 on 2022-01-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Main_category',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Sub_category',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
