# Generated by Django 4.0.1 on 2022-01-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_main_category_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Main_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
