# Generated by Django 4.0.1 on 2022-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
